
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:233 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:233 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Compilers/ArmCompilerforEmbedded6.22/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags:  
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:233 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Compilers/ArmCompilerforEmbedded6.22/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -c 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:233 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Compilers/ArmCompilerforEmbedded6.22/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -Aa 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:233 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Compilers/ArmCompilerforEmbedded6.22/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:233 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Compilers/ArmCompilerforEmbedded6.22/bin/armclang.exe 
      Build flags: -mcpu=Cortex-M55;-mfloat-abi=hard
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      0
      armclang: warning: '-mfloat-abi=hard': selected processor lacks floating point registers [-Wunsupported-abi]
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is ARMClang, found in:
        C:/Users/chrfav01/benchresults/cmsis/CMSIS-DSP/Examples/cmsis_build/cprj/tmp/convolution/VHT-Corstone-300/Release/CMakeFiles/3.29.3/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:233 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/chrfav01/benchresults/cmsis/CMSIS-DSP/Examples/cmsis_build/cprj/tmp/convolution/VHT-Corstone-300/Release/CMakeFiles/CMakeScratch/TryCompile-0p8r8a"
      binary: "C:/Users/chrfav01/benchresults/cmsis/CMSIS-DSP/Examples/cmsis_build/cprj/tmp/convolution/VHT-Corstone-300/Release/CMakeFiles/CMakeScratch/TryCompile-0p8r8a"
    cmakeVariables:
      CMAKE_C_COMPILER_TARGET: "arm-arm-none-eabi"
      CMAKE_C_FLAGS: "-mcpu=Cortex-M55 -mfloat-abi=hard"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "C:/ctools/etc/CMakeASM"
      CMAKE_WARN_DEPRECATED: "FALSE"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/chrfav01/benchresults/cmsis/CMSIS-DSP/Examples/cmsis_build/cprj/tmp/convolution/VHT-Corstone-300/Release/CMakeFiles/CMakeScratch/TryCompile-0p8r8a'
        
        Run Build Command(s): C:/ctools/bin/ninja.exe -v cmTC_3ce5d
        [1/2] C:\\Compilers\\ArmCompilerforEmbedded6.22\\bin\\armclang.exe --target=arm-arm-none-eabi   -mcpu=Cortex-M55 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -MF CMakeFiles\\cmTC_3ce5d.dir\\CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"
        Product: Hardware Success Kit (Early Access)
        Component: Arm Compiler for Embedded 6.22
        Tool: armclang [5ee92100]
        
        Target: arm-arm-none-eabi
         (in-process)
         "C:\\\\Compilers\\\\ArmCompilerforEmbedded6.22\\\\bin\\\\armclang.exe" -cc1 -triple thumbv8.1m.main-arm-none-eabihf -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign,preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m55 -target-feature +vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature +vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature +fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature +fullfp16 -target-feature +fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame "-fdebug-compilation-dir=C:\\\\Users\\\\chrfav01\\\\benchresults\\\\cmsis\\\\CMSIS-DSP\\\\Examples\\\\cmsis_build\\\\cprj\\\\tmp\\\\convolution\\\\VHT-Corstone-300\\\\Release\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-0p8r8a" -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=C:\\\\Users\\\\chrfav01\\\\benchresults\\\\cmsis\\\\CMSIS-DSP\\\\Examples\\\\cmsis_build\\\\cprj\\\\tmp\\\\convolution\\\\VHT-Corstone-300\\\\Release\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-0p8r8a" -resource-dir "C:\\\\Compilers\\\\ArmCompilerforEmbedded6.22\\\\lib\\\\clang\\\\19" -dependency-file "CMakeFiles\\\\cmTC_3ce5d.dir\\\\CMakeCCompilerABI.o.d" -MT CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem "C:\\\\Compilers\\\\ArmCompilerforEmbedded6.22\\\\bin\\\\..\\\\include" -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -x c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"\x0d
        Arm Compiler for Embedded 6.22 -cc1 default target aarch64-arm-none-eabi\x0d
        #include "..." search starts here:\x0d
        #include <...> search starts here:\x0d
         C:\\Compilers\\ArmCompilerforEmbedded6.22\\bin\\..\\include\x0d
        End of search list.\x0d
        [2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Compilers\\ArmCompilerforEmbedded6.22\\bin\\armar.exe --create -cr libcmTC_3ce5d.a  CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o && cd ."
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:137 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:233 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [C:/Compilers/ArmCompilerforEmbedded6.22/bin/../include]
        end of search list found
        collapse include dir [C:/Compilers/ArmCompilerforEmbedded6.22/bin/../include] ==> [C:/Compilers/ArmCompilerforEmbedded6.22/include]
        implicit include dirs: [C:/Compilers/ArmCompilerforEmbedded6.22/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:233 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(armlink\\.exe|;ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(armlink\\.exe|;ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: 'C:/Users/chrfav01/benchresults/cmsis/CMSIS-DSP/Examples/cmsis_build/cprj/tmp/convolution/VHT-Corstone-300/Release/CMakeFiles/CMakeScratch/TryCompile-0p8r8a']
        ignore line: []
        ignore line: [Run Build Command(s): C:/ctools/bin/ninja.exe -v cmTC_3ce5d]
        ignore line: [[1/2] C:\\Compilers\\ArmCompilerforEmbedded6.22\\bin\\armclang.exe --target=arm-arm-none-eabi   -mcpu=Cortex-M55 -mfloat-abi=hard    -v -MD -MT CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -MF CMakeFiles\\cmTC_3ce5d.dir\\CMakeCCompilerABI.o.d -o CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"]
        ignore line: [Product: Hardware Success Kit (Early Access)]
        ignore line: [Component: Arm Compiler for Embedded 6.22]
        ignore line: [Tool: armclang [5ee92100]]
        ignore line: []
        ignore line: [Target: arm-arm-none-eabi]
        ignore line: [ (in-process)]
        ignore line: [ "C:\\\\Compilers\\\\ArmCompilerforEmbedded6.22\\\\bin\\\\armclang.exe" -cc1 -triple thumbv8.1m.main-arm-none-eabihf -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -fdenormal-fp-math=preserve-sign preserve-sign -ffp-contract=on -fno-rounding-math -ffinite-math-only -mconstructor-aliases -target-cpu cortex-m55 -target-feature +vfp2 -target-feature +vfp2sp -target-feature -vfp3 -target-feature +vfp3d16 -target-feature +vfp3d16sp -target-feature -vfp3sp -target-feature +fp16 -target-feature -vfp4 -target-feature +vfp4d16 -target-feature +vfp4d16sp -target-feature -vfp4sp -target-feature -fp-armv8 -target-feature +fp-armv8d16 -target-feature +fp-armv8d16sp -target-feature -fp-armv8sp -target-feature +fullfp16 -target-feature +fp64 -target-feature -d32 -target-feature -neon -target-feature -sha2 -target-feature -aes -target-abi aapcs -mfloat-abi hard -debugger-tuning=gdb -fforce-dwarf-frame "-fdebug-compilation-dir=C:\\\\Users\\\\chrfav01\\\\benchresults\\\\cmsis\\\\CMSIS-DSP\\\\Examples\\\\cmsis_build\\\\cprj\\\\tmp\\\\convolution\\\\VHT-Corstone-300\\\\Release\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-0p8r8a" -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=C:\\\\Users\\\\chrfav01\\\\benchresults\\\\cmsis\\\\CMSIS-DSP\\\\Examples\\\\cmsis_build\\\\cprj\\\\tmp\\\\convolution\\\\VHT-Corstone-300\\\\Release\\\\CMakeFiles\\\\CMakeScratch\\\\TryCompile-0p8r8a" -resource-dir "C:\\\\Compilers\\\\ArmCompilerforEmbedded6.22\\\\lib\\\\clang\\\\19" -dependency-file "CMakeFiles\\\\cmTC_3ce5d.dir\\\\CMakeCCompilerABI.o.d" -MT CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -sys-header-deps -internal-isystem "C:\\\\Compilers\\\\ArmCompilerforEmbedded6.22\\\\bin\\\\..\\\\include" -nobuiltininc -ferror-limit 19 -fvisibility=hidden -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fsuppress-licensing -aggressive-jump-threading -o CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o -x c "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeCCompilerABI.c"\x0d]
        ignore line: [Arm Compiler for Embedded 6.22 -cc1 default target aarch64-arm-none-eabi\x0d]
        ignore line: [#include "..." search starts here:\x0d]
        ignore line: [#include <...> search starts here:\x0d]
        ignore line: [ C:\\Compilers\\ArmCompilerforEmbedded6.22\\bin\\..\\include\x0d]
        ignore line: [End of search list.\x0d]
        ignore line: [[2/2] C:\\Windows\\system32\\cmd.exe /C "cd . && C:\\Compilers\\ArmCompilerforEmbedded6.22\\bin\\armar.exe --create -cr libcmTC_3ce5d.a  CMakeFiles/cmTC_3ce5d.dir/CMakeCCompilerABI.o && cd ."]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
