/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'test.Release+IPSS_M0P' 
 * Target:  'Release+IPSS_M0P' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM0plus.h"



#endif /* RTE_COMPONENTS_H */
