/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0
 *
 * Project: 'bayes.Release+VHT-Corstone-310' 
 * Target:  'Release+VHT-Corstone-310' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE310MPS3.h"



#endif /* RTE_COMPONENTS_H */
