/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0
 *
 * Project: 'bayes.Release+VHT_M7' 
 * Target:  'Release+VHT_M7' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM7_DP.h"



#endif /* RTE_COMPONENTS_H */
