/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p38-gf512b381
 *
 * Project: 'example.Release+VHT-Corstone-300' 
 * Target:  'Release+VHT-Corstone-300' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE300MPS3.h"

/* ARM::Device:Native Driver:SysCounter@1.1.0 */
#define RTE_SYSCOUNTER      1
/* ARM::Device:Native Driver:Timeout@1.0.0 */
#define RTE_TIMEOUT      1


#endif /* RTE_COMPONENTS_H */
