var searchData=
[
  ['c_20extension_0',['C++ extension',['../group__DSPPP.html',1,'']]],
  ['canberra_20distance_1',['Canberra distance',['../group__Canberra.html',1,'']]],
  ['cascade_20filter_2',['High Precision Q31 Biquad Cascade Filter',['../group__BiquadCascadeDF1__32x64.html',1,'']]],
  ['cascade_20iir_20filters_20using_20a_20direct_20form_20ii_20transposed_20structure_3',['Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure',['../group__BiquadCascadeDF2T.html',1,'']]],
  ['cascade_20iir_20filters_20using_20direct_20form_20i_20structure_4',['Biquad Cascade IIR Filters Using Direct Form I Structure',['../group__BiquadCascadeDF1.html',1,'']]],
  ['cfft_5',['Buffer Sizes for CFFT',['../group__CFFTBuffers.html',1,'']]],
  ['chebyshev_20distance_6',['Chebyshev distance',['../group__Chebyshev.html',1,'']]],
  ['cholesky_20and_20ldlt_20decompositions_7',['Cholesky and LDLT decompositions',['../group__MatrixChol.html',1,'']]],
  ['cityblock_20manhattan_20distance_8',['Cityblock (Manhattan) distance',['../group__Manhattan.html',1,'']]],
  ['clarke_20transform_9',['Clarke Transform',['../group__clarke.html',1,'Vector Clarke Transform'],['../group__inv__clarke.html',1,'Vector Inverse Clarke Transform']]],
  ['class_20marks_20example_10',['Class Marks Example',['../group__ClassMarks.html',1,'']]],
  ['clipping_11',['Elementwise clipping',['../group__BasicClip.html',1,'']]],
  ['common_20types_20and_20constants_12',['Common types and constants',['../group__COMMON.html',1,'']]],
  ['complex_20by_20complex_20multiplication_13',['Complex-by-Complex Multiplication',['../group__CmplxByCmplxMult.html',1,'']]],
  ['complex_20by_20real_20multiplication_14',['Complex-by-Real Multiplication',['../group__CmplxByRealMult.html',1,'']]],
  ['complex_20conjugate_15',['Complex Conjugate',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product_16',['Complex Dot Product',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20double_17',['Complex Double',['../group__GenericComplexDoubleNumber.html',1,'']]],
  ['complex_20fft_20f16_18',['Complex FFT F16',['../group__ComplexFFTF16.html',1,'']]],
  ['complex_20fft_20f32_19',['Complex FFT F32',['../group__ComplexFFTF32.html',1,'']]],
  ['complex_20fft_20f64_20',['Complex FFT F64',['../group__ComplexFFTF64.html',1,'']]],
  ['complex_20fft_20functions_21',['Complex FFT Functions',['../group__ComplexFFT.html',1,'']]],
  ['complex_20fft_20functions_22',['Deprecated Complex FFT functions',['../group__ComplexFFTDeprecated.html',1,'']]],
  ['complex_20fft_20q15_23',['Complex FFT Q15',['../group__ComplexFFTQ15.html',1,'']]],
  ['complex_20fft_20q31_24',['Complex FFT Q31',['../group__ComplexFFTQ31.html',1,'']]],
  ['complex_20fft_20tables_25',['Complex FFT Tables',['../group__CFFT__CIFFT.html',1,'']]],
  ['complex_20float_26',['Complex Float',['../group__HeliumComplexFloatNumber.html',1,'Complex Float'],['../group__GenericComplexFloatNumber.html',1,'Complex Float']]],
  ['complex_20half_27',['Complex Half',['../group__HeliumComplexHalfNumber.html',1,'Complex Half'],['../group__GenericComplexHalfNumber.html',1,'Complex Half']]],
  ['complex_20magnitude_28',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared_29',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_20math_20functions_30',['Complex Math Functions',['../group__groupCmplxMath.html',1,'']]],
  ['complex_20matrix_20multiplication_31',['Complex Matrix Multiplication',['../group__CmplxMatrixMult.html',1,'']]],
  ['complex_20matrix_20transpose_32',['Complex Matrix Transpose',['../group__MatrixComplexTrans.html',1,'']]],
  ['complex_20multiplication_33',['Complex-by-Complex Multiplication',['../group__CmplxByCmplxMult.html',1,'']]],
  ['complex_20q15_34',['Complex Q15',['../group__HeliumComplexQ15Number.html',1,'Complex Q15'],['../group__GenericComplexQ15Number.html',1,'Complex Q15']]],
  ['complex_20q31_35',['Complex Q31',['../group__HeliumComplexQ31Number.html',1,'Complex Q31'],['../group__GenericComplexQ31Number.html',1,'Complex Q31']]],
  ['complex_20q7_36',['Complex Q7',['../group__GenericComplexQ7Number.html',1,'']]],
  ['conjugate_37',['Conjugate',['../group__cmplx__conj.html',1,'Complex Conjugate'],['../group__QuatConjugate.html',1,'Quaternion Conjugate']]],
  ['constants_38',['Common types and constants',['../group__COMMON.html',1,'']]],
  ['control_39',['PID Motor Control',['../group__PID.html',1,'']]],
  ['controller_20functions_40',['Controller Functions',['../group__groupController.html',1,'']]],
  ['convergence_20example_41',['Signal Convergence Example',['../group__SignalConvergence.html',1,'']]],
  ['conversions_42',['Quaternion conversions',['../group__QuatConv.html',1,'']]],
  ['convert_2016_20bit_20fixed_20point_20value_43',['Convert 16-bit fixed point value',['../group__q15__to__x.html',1,'']]],
  ['convert_2016_20bit_20floating_20point_20value_44',['Convert 16-bit floating point value',['../group__f16__to__x.html',1,'']]],
  ['convert_2032_20bit_20fixed_20point_20value_45',['Convert 32-bit fixed point value',['../group__q31__to__x.html',1,'']]],
  ['convert_2032_20bit_20floating_20point_20value_46',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['convert_2064_20bit_20floating_20point_20value_47',['Convert 64-bit floating point value',['../group__f64__to__x.html',1,'']]],
  ['convert_208_20bit_20fixed_20point_20value_48',['Convert 8-bit fixed point value',['../group__q7__to__x.html',1,'']]],
  ['convolution_49',['Convolution',['../group__Conv.html',1,'Convolution'],['../group__PartialConv.html',1,'Partial Convolution']]],
  ['convolution_20example_50',['Convolution Example',['../group__ConvolutionExample.html',1,'']]],
  ['copy_51',['Vector Copy',['../group__copy.html',1,'']]],
  ['correlation_52',['Correlation',['../group__Corr.html',1,'']]],
  ['correlation_20distance_53',['Correlation distance',['../group__Correlation.html',1,'']]],
  ['cosine_54',['Cosine',['../group__cos.html',1,'Cosine'],['../group__SinCos.html',1,'Sine Cosine']]],
  ['cosine_20distance_55',['Cosine distance',['../group__CosineDist.html',1,'']]],
  ['cubic_20spline_20interpolation_56',['Cubic Spline Interpolation',['../group__SplineInterpolate.html',1,'']]],
  ['curtis_20distance_57',['Bray-Curtis distance',['../group__braycurtis.html',1,'']]]
];
