var searchData=
[
  ['datatypes_0',['datatypes',['../group__FIXED.html',1,'Fixed point datatypes'],['../group__NUMBER.html',1,'Number datatypes']]],
  ['db_1',['dB',['../group__WindowBARTLETT.html',1,'Bartlett window function (26.5 dB)'],['../group__WindowBLACKMAN__HARRIS__92DB.html',1,'Blackman Harris window function (92 dB)'],['../group__WindowHAMMING.html',1,'Hamming window function (42.7 dB)'],['../group__WindowHANNING.html',1,'Hanning window function (31.5 dB)'],['../group__WindowHFT116D.html',1,'Hft116d window function (116.8 dB)'],['../group__WindowHFT144D.html',1,'Hft144d window function (144.1 dB)'],['../group__WindowHFT169D.html',1,'Hft169d window function (169.5 dB)'],['../group__WindowHFT196D.html',1,'Hft196d window function (196.2 dB)'],['../group__WindowHFT223D.html',1,'Hft223d window function (223.0 dB)'],['../group__WindowHFT248D.html',1,'Hft248d window function (248.4 dB)'],['../group__WindowHFT90D.html',1,'Hft90d window function (90.2 dB)'],['../group__WindowHFT95.html',1,'Hft95 window function (95.0 dB)'],['../group__WindowNUTTALL3.html',1,'Nuttall3 window function (46.7 dB)'],['../group__WindowNUTTALL3A.html',1,'Nuttall3a window function (64.2 dB)'],['../group__WindowNUTTALL3B.html',1,'Nuttall3b window function (71.5 dB)'],['../group__WindowNUTTALL4.html',1,'Nuttall4 window function (60.9 dB)'],['../group__WindowNUTTALL4A.html',1,'Nuttall4a window function (82.6 dB)'],['../group__WindowNUTTALL4B.html',1,'Nuttall4b window function (93.3 dB)'],['../group__WindowNUTTALL4C.html',1,'Nuttall4c window function (98.1 dB)'],['../group__WindowWELCH.html',1,'Welch window function (21.3 dB)']]],
  ['debugging_2',['Tools for debugging',['../group__DEBUG.html',1,'']]],
  ['decimator_3',['Finite Impulse Response (FIR) Decimator',['../group__FIR__decimate.html',1,'']]],
  ['decomposition_20of_20a_20matrix_4',['QR decomposition of a Matrix',['../group__MatrixQR.html',1,'']]],
  ['decompositions_5',['Cholesky and LDLT decompositions',['../group__MatrixChol.html',1,'']]],
  ['definitions_6',['definitions',['../group__DSPNumber.html',1,'DSP extension specific number definitions'],['../group__HeliumNumber.html',1,'Helium specific number definitions'],['../group__GenericNumber.html',1,'Scalar number definitions']]],
  ['deprecated_20complex_20fft_20functions_7',['Deprecated Complex FFT functions',['../group__ComplexFFTDeprecated.html',1,'']]],
  ['deprecated_20real_20fft_20functions_8',['Deprecated Real FFT Functions',['../group__DeprecatedRealFFT.html',1,'']]],
  ['detection_9',['Architecture detection',['../group__ARCH.html',1,'']]],
  ['deviation_10',['Standard deviation',['../group__STD.html',1,'']]],
  ['direct_20form_20i_20structure_11',['Biquad Cascade IIR Filters Using Direct Form I Structure',['../group__BiquadCascadeDF1.html',1,'']]],
  ['direct_20form_20ii_20transposed_20structure_12',['Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure',['../group__BiquadCascadeDF2T.html',1,'']]],
  ['distance_13',['Dynamic Time Warping Distance',['../group__DTW.html',1,'']]],
  ['distance_14',['distance',['../group__braycurtis.html',1,'Bray-Curtis distance'],['../group__Canberra.html',1,'Canberra distance'],['../group__Chebyshev.html',1,'Chebyshev distance'],['../group__Manhattan.html',1,'Cityblock (Manhattan) distance'],['../group__Correlation.html',1,'Correlation distance'],['../group__CosineDist.html',1,'Cosine distance'],['../group__Euclidean.html',1,'Euclidean distance'],['../group__JensenShannon.html',1,'Jensen-Shannon distance'],['../group__Minkowski.html',1,'Minkowski distance']]],
  ['distance_20functions_15',['Distance Functions',['../group__groupDistance.html',1,'']]],
  ['distances_16',['Distances',['../group__BoolDist.html',1,'Boolean Distances'],['../group__FloatDist.html',1,'Float Distances']]],
  ['divergence_17',['Kullback-Leibler divergence',['../group__Kullback-Leibler.html',1,'']]],
  ['division_18',['Fixed point division',['../group__divide.html',1,'']]],
  ['dot_20product_19',['Dot Product',['../group__cmplx__dot__prod.html',1,'Complex Dot Product'],['../group__BasicDotProd.html',1,'Vector Dot Product']]],
  ['dot_20product_20example_20',['Dot Product Example',['../group__DotproductExample.html',1,'']]],
  ['double_21',['Double',['../group__GenericComplexDoubleNumber.html',1,'Complex Double'],['../group__GenericDoubleNumber.html',1,'Double']]],
  ['dsp_20extension_20specific_20algorithm_22',['DSP Extension specific algorithm',['../group__DSPALG.html',1,'']]],
  ['dsp_20extension_20specific_20number_20definitions_23',['DSP extension specific number definitions',['../group__DSPNumber.html',1,'']]],
  ['dsp_20vector_20and_20memory_20allocator_20example_24',['DSP++ Vector and Memory Allocator Example',['../group__DspppExample.html',1,'']]],
  ['durbin_20algorithm_25',['Levinson Durbin Algorithm',['../group__LD.html',1,'']]],
  ['dynamic_20time_20warping_20distance_26',['Dynamic Time Warping Distance',['../group__DTW.html',1,'']]]
];
