var searchData=
[
  ['bartlett_20window_20function_2026_205_20db_0',['Bartlett window function (26.5 dB)',['../group__WindowBARTLETT.html',1,'']]],
  ['barycenter_1',['Barycenter',['../group__barycenter.html',1,'']]],
  ['basic_20math_20functions_2',['Basic Math Functions',['../group__groupMath.html',1,'']]],
  ['bayes_20example_3',['Bayes Example',['../group__BayesExample.html',1,'']]],
  ['bayesian_20estimators_4',['Bayesian estimators',['../group__groupBayes.html',1,'']]],
  ['bilinear_20interpolation_5',['Bilinear Interpolation',['../group__BilinearInterpolate.html',1,'']]],
  ['bin_20example_6',['Frequency Bin Example',['../group__FrequencyBin.html',1,'']]],
  ['biquad_20cascade_20filter_7',['High Precision Q31 Biquad Cascade Filter',['../group__BiquadCascadeDF1__32x64.html',1,'']]],
  ['biquad_20cascade_20iir_20filters_20using_20a_20direct_20form_20ii_20transposed_20structure_8',['Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure',['../group__BiquadCascadeDF2T.html',1,'']]],
  ['biquad_20cascade_20iir_20filters_20using_20direct_20form_20i_20structure_9',['Biquad Cascade IIR Filters Using Direct Form I Structure',['../group__BiquadCascadeDF1.html',1,'']]],
  ['bit_20fixed_20point_20value_10',['bit fixed point value',['../group__q15__to__x.html',1,'Convert 16-bit fixed point value'],['../group__q31__to__x.html',1,'Convert 32-bit fixed point value'],['../group__q7__to__x.html',1,'Convert 8-bit fixed point value']]],
  ['bit_20floating_20point_20value_11',['bit floating point value',['../group__f16__to__x.html',1,'Convert 16-bit floating point value'],['../group__float__to__x.html',1,'Convert 32-bit floating point value'],['../group__f64__to__x.html',1,'Convert 64-bit floating point value']]],
  ['bitwise_20and_12',['Vector bitwise AND',['../group__And.html',1,'']]],
  ['bitwise_20exclusive_20or_13',['Vector bitwise exclusive OR',['../group__Xor.html',1,'']]],
  ['bitwise_20inclusive_20or_14',['Vector bitwise inclusive OR',['../group__Or.html',1,'']]],
  ['bitwise_20not_15',['Vector bitwise NOT',['../group__Not.html',1,'']]],
  ['blackman_20harris_20window_20function_2092_20db_16',['Blackman Harris window function (92 dB)',['../group__WindowBLACKMAN__HARRIS__92DB.html',1,'']]],
  ['boolean_20distances_17',['Boolean Distances',['../group__BoolDist.html',1,'']]],
  ['bray_20curtis_20distance_18',['Bray-Curtis distance',['../group__braycurtis.html',1,'']]],
  ['buffer_20allocator_19',['buffer allocator',['../group__MEMBUF.html',1,'Memory buffer allocator'],['../group__MEMVEC.html',1,'Vector / matrix buffer allocator']]],
  ['buffer_20size_20functions_20',['Enumerations for transform buffer size functions',['../group__bufferSizeTypes.html',1,'']]],
  ['buffer_20sizes_21',['Transform Buffer Sizes',['../group__TransformBuffers.html',1,'']]],
  ['buffer_20sizes_20for_20cfft_22',['Buffer Sizes for CFFT',['../group__CFFTBuffers.html',1,'']]],
  ['buffer_20sizes_20for_20mfcc_23',['Buffer Sizes for MFCC',['../group__MFCCBuffers.html',1,'']]],
  ['buffer_20sizes_20for_20rfft_24',['Buffer Sizes for RFFT',['../group__RFFTBuffers.html',1,'']]],
  ['by_20complex_20multiplication_25',['Complex-by-Complex Multiplication',['../group__CmplxByCmplxMult.html',1,'']]],
  ['by_20real_20multiplication_26',['Complex-by-Real Multiplication',['../group__CmplxByRealMult.html',1,'']]]
];
