var searchData=
[
  ['canberra_20distance_0',['Canberra distance',['../group__Canberra.html',1,'']]],
  ['chebyshev_20distance_1',['Chebyshev distance',['../group__Chebyshev.html',1,'']]],
  ['cholesky_20and_20ldlt_20decompositions_2',['Cholesky and LDLT decompositions',['../group__MatrixChol.html',1,'']]],
  ['cityblock_20_28manhattan_29_20distance_3',['Cityblock (Manhattan) distance',['../group__Manhattan.html',1,'']]],
  ['class_20marks_20example_4',['Class Marks Example',['../group__ClassMarks.html',1,'']]],
  ['complex_20conjugate_5',['Complex Conjugate',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product_6',['Complex Dot Product',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20fft_20f16_7',['Complex FFT F16',['../group__ComplexFFTF16.html',1,'']]],
  ['complex_20fft_20f32_8',['Complex FFT F32',['../group__ComplexFFTF32.html',1,'']]],
  ['complex_20fft_20f64_9',['Complex FFT F64',['../group__ComplexFFTF64.html',1,'']]],
  ['complex_20fft_20functions_10',['Complex FFT Functions',['../group__ComplexFFT.html',1,'']]],
  ['complex_20fft_20q15_11',['Complex FFT Q15',['../group__ComplexFFTQ15.html',1,'']]],
  ['complex_20fft_20q31_12',['Complex FFT Q31',['../group__ComplexFFTQ31.html',1,'']]],
  ['complex_20fft_20tables_13',['Complex FFT Tables',['../group__CFFT__CIFFT.html',1,'']]],
  ['complex_20magnitude_14',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared_15',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_20math_20functions_16',['Complex Math Functions',['../group__groupCmplxMath.html',1,'']]],
  ['complex_20matrix_20multiplication_17',['Complex Matrix Multiplication',['../group__CmplxMatrixMult.html',1,'']]],
  ['complex_20matrix_20transpose_18',['Complex Matrix Transpose',['../group__MatrixComplexTrans.html',1,'']]],
  ['complex_2dby_2dcomplex_20multiplication_19',['Complex-by-Complex Multiplication',['../group__CmplxByCmplxMult.html',1,'']]],
  ['complex_2dby_2dreal_20multiplication_20',['Complex-by-Real Multiplication',['../group__CmplxByRealMult.html',1,'']]],
  ['controller_20functions_21',['Controller Functions',['../group__groupController.html',1,'']]],
  ['convert_2016_2dbit_20fixed_20point_20value_22',['Convert 16-bit fixed point value',['../group__q15__to__x.html',1,'']]],
  ['convert_2016_2dbit_20floating_20point_20value_23',['Convert 16-bit floating point value',['../group__f16__to__x.html',1,'']]],
  ['convert_2032_2dbit_20fixed_20point_20value_24',['Convert 32-bit fixed point value',['../group__q31__to__x.html',1,'']]],
  ['convert_2032_2dbit_20floating_20point_20value_25',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['convert_2064_2dbit_20floating_20point_20value_26',['Convert 64-bit floating point value',['../group__f64__to__x.html',1,'']]],
  ['convert_208_2dbit_20fixed_20point_20value_27',['Convert 8-bit fixed point value',['../group__q7__to__x.html',1,'']]],
  ['convolution_28',['Convolution',['../group__Conv.html',1,'']]],
  ['convolution_20example_29',['Convolution Example',['../group__ConvolutionExample.html',1,'']]],
  ['correlation_30',['Correlation',['../group__Corr.html',1,'']]],
  ['correlation_20distance_31',['Correlation distance',['../group__Correlation.html',1,'']]],
  ['cosine_32',['Cosine',['../group__cos.html',1,'']]],
  ['cosine_20distance_33',['Cosine distance',['../group__CosineDist.html',1,'']]],
  ['cubic_20spline_20interpolation_34',['Cubic Spline Interpolation',['../group__SplineInterpolate.html',1,'']]]
];
