var searchData=
[
  ['f16_0',['F16',['../group__ComplexFFTF16.html',1,'Complex FFT F16'],['../group__MFCCF16.html',1,'MFCC F16']]],
  ['f16_20functions_1',['Real FFT F16 Functions',['../group__RealFFTF16.html',1,'']]],
  ['f32_2',['F32',['../group__ComplexFFTF32.html',1,'Complex FFT F32'],['../group__MFCCF32.html',1,'MFCC F32']]],
  ['f32_20functions_3',['Real FFT F32 Functions',['../group__RealFFTF32.html',1,'']]],
  ['f64_4',['Complex FFT F64',['../group__ComplexFFTF64.html',1,'']]],
  ['f64_20functions_5',['Real FFT F64 Functions',['../group__RealFFTF64.html',1,'']]],
  ['fast_20math_20functions_6',['Fast Math Functions',['../group__groupFastMath.html',1,'']]],
  ['fft_20f16_7',['Complex FFT F16',['../group__ComplexFFTF16.html',1,'']]],
  ['fft_20f16_20functions_8',['Real FFT F16 Functions',['../group__RealFFTF16.html',1,'']]],
  ['fft_20f32_9',['Complex FFT F32',['../group__ComplexFFTF32.html',1,'']]],
  ['fft_20f32_20functions_10',['Real FFT F32 Functions',['../group__RealFFTF32.html',1,'']]],
  ['fft_20f64_11',['Complex FFT F64',['../group__ComplexFFTF64.html',1,'']]],
  ['fft_20f64_20functions_12',['Real FFT F64 Functions',['../group__RealFFTF64.html',1,'']]],
  ['fft_20functions_13',['FFT Functions',['../group__ComplexFFT.html',1,'Complex FFT Functions'],['../group__DeprecatedRealFFT.html',1,'Deprecated Real FFT Functions'],['../group__RealFFT.html',1,'Real FFT Functions']]],
  ['fft_20functions_14',['Deprecated Complex FFT functions',['../group__ComplexFFTDeprecated.html',1,'']]],
  ['fft_20q15_15',['Complex FFT Q15',['../group__ComplexFFTQ15.html',1,'']]],
  ['fft_20q15_20functions_16',['Real FFT Q15 Functions',['../group__RealFFTQ15.html',1,'']]],
  ['fft_20q31_17',['Complex FFT Q31',['../group__ComplexFFTQ31.html',1,'']]],
  ['fft_20q31_20functions_18',['Real FFT Q31 Functions',['../group__RealFFTQ31.html',1,'']]],
  ['fft_20tables_19',['FFT Tables',['../group__CFFT__CIFFT.html',1,'Complex FFT Tables'],['../group__RealFFT__Table.html',1,'Real FFT Tables']]],
  ['fill_20',['Vector Fill',['../group__Fill.html',1,'']]],
  ['filter_21',['High Precision Q31 Biquad Cascade Filter',['../group__BiquadCascadeDF1__32x64.html',1,'']]],
  ['filter_20example_22',['FIR Lowpass Filter Example',['../group__FIRLPF.html',1,'']]],
  ['filtering_20functions_23',['Filtering Functions',['../group__groupFilters.html',1,'']]],
  ['filters_24',['Filters',['../group__FIR.html',1,'Finite Impulse Response (FIR) Filters'],['../group__FIR__Lattice.html',1,'Finite Impulse Response (FIR) Lattice Filters'],['../group__FIR__Sparse.html',1,'Finite Impulse Response (FIR) Sparse Filters'],['../group__IIR__Lattice.html',1,'Infinite Impulse Response (IIR) Lattice Filters'],['../group__LMS.html',1,'Least Mean Square (LMS) Filters'],['../group__LMS__NORM.html',1,'Normalized LMS Filters']]],
  ['filters_20using_20a_20direct_20form_20ii_20transposed_20structure_25',['Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure',['../group__BiquadCascadeDF2T.html',1,'']]],
  ['filters_20using_20direct_20form_20i_20structure_26',['Biquad Cascade IIR Filters Using Direct Form I Structure',['../group__BiquadCascadeDF1.html',1,'']]],
  ['finite_20impulse_20response_20fir_20decimator_27',['Finite Impulse Response (FIR) Decimator',['../group__FIR__decimate.html',1,'']]],
  ['finite_20impulse_20response_20fir_20filters_28',['Finite Impulse Response (FIR) Filters',['../group__FIR.html',1,'']]],
  ['finite_20impulse_20response_20fir_20interpolator_29',['Finite Impulse Response (FIR) Interpolator',['../group__FIR__Interpolate.html',1,'']]],
  ['finite_20impulse_20response_20fir_20lattice_20filters_30',['Finite Impulse Response (FIR) Lattice Filters',['../group__FIR__Lattice.html',1,'']]],
  ['finite_20impulse_20response_20fir_20sparse_20filters_31',['Finite Impulse Response (FIR) Sparse Filters',['../group__FIR__Sparse.html',1,'']]],
  ['fir_20decimator_32',['Finite Impulse Response (FIR) Decimator',['../group__FIR__decimate.html',1,'']]],
  ['fir_20filters_33',['Finite Impulse Response (FIR) Filters',['../group__FIR.html',1,'']]],
  ['fir_20interpolator_34',['Finite Impulse Response (FIR) Interpolator',['../group__FIR__Interpolate.html',1,'']]],
  ['fir_20lattice_20filters_35',['Finite Impulse Response (FIR) Lattice Filters',['../group__FIR__Lattice.html',1,'']]],
  ['fir_20lowpass_20filter_20example_36',['FIR Lowpass Filter Example',['../group__FIRLPF.html',1,'']]],
  ['fir_20sparse_20filters_37',['Finite Impulse Response (FIR) Sparse Filters',['../group__FIR__Sparse.html',1,'']]],
  ['fixed_20point_20datatypes_38',['Fixed point datatypes',['../group__FIXED.html',1,'']]],
  ['fixed_20point_20division_39',['Fixed point division',['../group__divide.html',1,'']]],
  ['fixed_20point_20value_40',['fixed point value',['../group__q15__to__x.html',1,'Convert 16-bit fixed point value'],['../group__q31__to__x.html',1,'Convert 32-bit fixed point value'],['../group__q7__to__x.html',1,'Convert 8-bit fixed point value']]],
  ['flat_20top_20window_20functions_41',['Flat-top window functions',['../group__WindowFlat.html',1,'']]],
  ['float_42',['Float',['../group__HeliumComplexFloatNumber.html',1,'Complex Float'],['../group__GenericComplexFloatNumber.html',1,'Complex Float'],['../group__HeliumFloatNumber.html',1,'Float'],['../group__GenericFloatNumber.html',1,'Float']]],
  ['float_20distances_43',['Float Distances',['../group__FloatDist.html',1,'']]],
  ['floating_20point_20value_44',['floating point value',['../group__f16__to__x.html',1,'Convert 16-bit floating point value'],['../group__float__to__x.html',1,'Convert 32-bit floating point value'],['../group__f64__to__x.html',1,'Convert 64-bit floating point value']]],
  ['for_20cfft_45',['Buffer Sizes for CFFT',['../group__CFFTBuffers.html',1,'']]],
  ['for_20debugging_46',['Tools for debugging',['../group__DEBUG.html',1,'']]],
  ['for_20fusion_47',['Abstract syntax tree for fusion',['../group__FUSION.html',1,'']]],
  ['for_20memory_48',['Miscellaneous utilities for memory',['../group__MEMTOOL.html',1,'']]],
  ['for_20mfcc_49',['Buffer Sizes for MFCC',['../group__MFCCBuffers.html',1,'']]],
  ['for_20rfft_50',['Buffer Sizes for RFFT',['../group__RFFTBuffers.html',1,'']]],
  ['for_20transform_20buffer_20size_20functions_51',['Enumerations for transform buffer size functions',['../group__bufferSizeTypes.html',1,'']]],
  ['form_20i_20structure_52',['Biquad Cascade IIR Filters Using Direct Form I Structure',['../group__BiquadCascadeDF1.html',1,'']]],
  ['form_20ii_20transposed_20structure_53',['Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure',['../group__BiquadCascadeDF2T.html',1,'']]],
  ['frequency_20bin_20example_54',['Frequency Bin Example',['../group__FrequencyBin.html',1,'']]],
  ['function_20116_208_20db_55',['Hft116d window function (116.8 dB)',['../group__WindowHFT116D.html',1,'']]],
  ['function_20144_201_20db_56',['Hft144d window function (144.1 dB)',['../group__WindowHFT144D.html',1,'']]],
  ['function_20169_205_20db_57',['Hft169d window function (169.5 dB)',['../group__WindowHFT169D.html',1,'']]],
  ['function_20196_202_20db_58',['Hft196d window function (196.2 dB)',['../group__WindowHFT196D.html',1,'']]],
  ['function_2021_203_20db_59',['Welch window function (21.3 dB)',['../group__WindowWELCH.html',1,'']]],
  ['function_20223_200_20db_60',['Hft223d window function (223.0 dB)',['../group__WindowHFT223D.html',1,'']]],
  ['function_20248_204_20db_61',['Hft248d window function (248.4 dB)',['../group__WindowHFT248D.html',1,'']]],
  ['function_2026_205_20db_62',['Bartlett window function (26.5 dB)',['../group__WindowBARTLETT.html',1,'']]],
  ['function_2031_205_20db_63',['Hanning window function (31.5 dB)',['../group__WindowHANNING.html',1,'']]],
  ['function_2042_207_20db_64',['Hamming window function (42.7 dB)',['../group__WindowHAMMING.html',1,'']]],
  ['function_2046_207_20db_65',['Nuttall3 window function (46.7 dB)',['../group__WindowNUTTALL3.html',1,'']]],
  ['function_2060_209_20db_66',['Nuttall4 window function (60.9 dB)',['../group__WindowNUTTALL4.html',1,'']]],
  ['function_2064_202_20db_67',['Nuttall3a window function (64.2 dB)',['../group__WindowNUTTALL3A.html',1,'']]],
  ['function_2071_205_20db_68',['Nuttall3b window function (71.5 dB)',['../group__WindowNUTTALL3B.html',1,'']]],
  ['function_2082_206_20db_69',['Nuttall4a window function (82.6 dB)',['../group__WindowNUTTALL4A.html',1,'']]],
  ['function_2090_202_20db_70',['Hft90d window function (90.2 dB)',['../group__WindowHFT90D.html',1,'']]],
  ['function_2092_20db_71',['Blackman Harris window function (92 dB)',['../group__WindowBLACKMAN__HARRIS__92DB.html',1,'']]],
  ['function_2093_203_20db_72',['Nuttall4b window function (93.3 dB)',['../group__WindowNUTTALL4B.html',1,'']]],
  ['function_2095_200_20db_73',['Hft95 window function (95.0 dB)',['../group__WindowHFT95.html',1,'']]],
  ['function_2098_201_20db_74',['Nuttall4c window function (98.1 dB)',['../group__WindowNUTTALL4C.html',1,'']]],
  ['functions_75',['Functions',['../group__groupMath.html',1,'Basic Math Functions'],['../group__ComplexFFT.html',1,'Complex FFT Functions'],['../group__groupCmplxMath.html',1,'Complex Math Functions'],['../group__groupController.html',1,'Controller Functions'],['../group__DeprecatedRealFFT.html',1,'Deprecated Real FFT Functions'],['../group__groupDistance.html',1,'Distance Functions'],['../group__groupFastMath.html',1,'Fast Math Functions'],['../group__groupFilters.html',1,'Filtering Functions'],['../group__groupInterpolation.html',1,'Interpolation Functions'],['../group__groupMatrix.html',1,'Matrix Functions'],['../group__groupQuaternionMath.html',1,'Quaternion Math Functions'],['../group__RealFFTF16.html',1,'Real FFT F16 Functions'],['../group__RealFFTF32.html',1,'Real FFT F32 Functions'],['../group__RealFFTF64.html',1,'Real FFT F64 Functions'],['../group__RealFFT.html',1,'Real FFT Functions'],['../group__RealFFTQ15.html',1,'Real FFT Q15 Functions'],['../group__RealFFTQ31.html',1,'Real FFT Q31 Functions'],['../group__groupStats.html',1,'Statistics Functions'],['../group__groupSupport.html',1,'Support Functions'],['../group__groupSVM.html',1,'SVM Functions'],['../group__groupTransforms.html',1,'Transform Functions'],['../group__groupWindow.html',1,'Window Functions']]],
  ['functions_76',['functions',['../group__Accumulation.html',1,'Accumulation functions'],['../group__ComplexFFTDeprecated.html',1,'Deprecated Complex FFT functions'],['../group__bufferSizeTypes.html',1,'Enumerations for transform buffer size functions'],['../group__WindowFlat.html',1,'Flat-top window functions'],['../group__WindowNormal.html',1,'Regular window functions']]],
  ['fusion_77',['Abstract syntax tree for fusion',['../group__FUSION.html',1,'']]]
];
