var searchData=
[
  ['scalar_20algorithm_0',['Scalar algorithm',['../group__SCALARALG.html',1,'']]],
  ['scalar_20number_20definitions_1',['Scalar number definitions',['../group__GenericNumber.html',1,'']]],
  ['scale_2',['Scale',['../group__MatrixScale.html',1,'Matrix Scale'],['../group__BasicScale.html',1,'Vector Scale']]],
  ['shannon_20distance_3',['Jensen-Shannon distance',['../group__JensenShannon.html',1,'']]],
  ['shift_4',['Vector Shift',['../group__BasicShift.html',1,'']]],
  ['sigmoid_20svm_5',['Sigmoid SVM',['../group__sigmoidsvm.html',1,'']]],
  ['signal_20convergence_20example_6',['Signal Convergence Example',['../group__SignalConvergence.html',1,'']]],
  ['sine_7',['Sine',['../group__sin.html',1,'']]],
  ['sine_20cosine_8',['Sine Cosine',['../group__SinCos.html',1,'']]],
  ['sinecosine_20example_9',['SineCosine Example',['../group__SinCosExample.html',1,'']]],
  ['size_20functions_10',['Enumerations for transform buffer size functions',['../group__bufferSizeTypes.html',1,'']]],
  ['sizes_11',['Transform Buffer Sizes',['../group__TransformBuffers.html',1,'']]],
  ['sizes_20for_20cfft_12',['Buffer Sizes for CFFT',['../group__CFFTBuffers.html',1,'']]],
  ['sizes_20for_20mfcc_13',['Buffer Sizes for MFCC',['../group__MFCCBuffers.html',1,'']]],
  ['sizes_20for_20rfft_14',['Buffer Sizes for RFFT',['../group__RFFTBuffers.html',1,'']]],
  ['sorting_20algorithms_15',['Vector sorting algorithms',['../group__Sorting.html',1,'']]],
  ['sparse_20filters_16',['Finite Impulse Response (FIR) Sparse Filters',['../group__FIR__Sparse.html',1,'']]],
  ['specific_20algorithm_17',['specific algorithm',['../group__ARCHALG.html',1,'Architecture specific algorithm'],['../group__DSPALG.html',1,'DSP Extension specific algorithm'],['../group__HELIUMALG.html',1,'Helium specific algorithm']]],
  ['specific_20number_20definitions_18',['specific number definitions',['../group__DSPNumber.html',1,'DSP extension specific number definitions'],['../group__HeliumNumber.html',1,'Helium specific number definitions']]],
  ['spline_20interpolation_19',['Cubic Spline Interpolation',['../group__SplineInterpolate.html',1,'']]],
  ['square_20error_20',['Mean Square Error',['../group__MSE.html',1,'']]],
  ['square_20lms_20filters_21',['Least Mean Square (LMS) Filters',['../group__LMS.html',1,'']]],
  ['square_20rms_22',['Root mean square (RMS)',['../group__RMS.html',1,'']]],
  ['square_20root_23',['Square Root',['../group__SQRT.html',1,'']]],
  ['squared_24',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['standard_20deviation_25',['Standard deviation',['../group__STD.html',1,'']]],
  ['statistics_20functions_26',['Statistics Functions',['../group__groupStats.html',1,'']]],
  ['structure_27',['Structure',['../group__BiquadCascadeDF2T.html',1,'Biquad Cascade IIR Filters Using a Direct Form II Transposed Structure'],['../group__BiquadCascadeDF1.html',1,'Biquad Cascade IIR Filters Using Direct Form I Structure']]],
  ['subtraction_28',['Subtraction',['../group__MatrixSub.html',1,'Matrix Subtraction'],['../group__BasicSub.html',1,'Vector Subtraction']]],
  ['support_20functions_29',['Support Functions',['../group__groupSupport.html',1,'']]],
  ['svm_30',['SVM',['../group__linearsvm.html',1,'Linear SVM'],['../group__polysvm.html',1,'Polynomial SVM'],['../group__rbfsvm.html',1,'RBF SVM'],['../group__sigmoidsvm.html',1,'Sigmoid SVM']]],
  ['svm_20example_31',['SVM Example',['../group__SVMExample.html',1,'']]],
  ['svm_20functions_32',['SVM Functions',['../group__groupSVM.html',1,'']]],
  ['syntax_20tree_20for_20fusion_33',['Abstract syntax tree for fusion',['../group__FUSION.html',1,'']]]
];
