var searchData=
[
  ['value_0',['Vector Absolute Value',['../group__BasicAbs.html',1,'']]],
  ['value_1',['value',['../group__q15__to__x.html',1,'Convert 16-bit fixed point value'],['../group__f16__to__x.html',1,'Convert 16-bit floating point value'],['../group__q31__to__x.html',1,'Convert 32-bit fixed point value'],['../group__float__to__x.html',1,'Convert 32-bit floating point value'],['../group__f64__to__x.html',1,'Convert 64-bit floating point value'],['../group__q7__to__x.html',1,'Convert 8-bit fixed point value']]],
  ['variance_2',['Variance',['../group__variance.html',1,'']]],
  ['variance_20example_3',['Variance Example',['../group__VarianceExample.html',1,'']]],
  ['vector_4',['Householder transform of a vector',['../group__MatrixHouseholder.html',1,'']]],
  ['vector_20absolute_20value_5',['Vector Absolute Value',['../group__BasicAbs.html',1,'']]],
  ['vector_20addition_6',['Vector Addition',['../group__BasicAdd.html',1,'']]],
  ['vector_20and_20memory_20allocator_20example_7',['DSP++ Vector and Memory Allocator Example',['../group__DspppExample.html',1,'']]],
  ['vector_20bitwise_20and_8',['Vector bitwise AND',['../group__And.html',1,'']]],
  ['vector_20bitwise_20exclusive_20or_9',['Vector bitwise exclusive OR',['../group__Xor.html',1,'']]],
  ['vector_20bitwise_20inclusive_20or_10',['Vector bitwise inclusive OR',['../group__Or.html',1,'']]],
  ['vector_20bitwise_20not_11',['Vector bitwise NOT',['../group__Not.html',1,'']]],
  ['vector_20clarke_20transform_12',['Vector Clarke Transform',['../group__clarke.html',1,'']]],
  ['vector_20copy_13',['Vector Copy',['../group__copy.html',1,'']]],
  ['vector_20dot_20product_14',['Vector Dot Product',['../group__BasicDotProd.html',1,'']]],
  ['vector_20exponential_15',['Vector Exponential',['../group__vexp.html',1,'']]],
  ['vector_20fill_16',['Vector Fill',['../group__Fill.html',1,'']]],
  ['vector_20inverse_20clarke_20transform_17',['Vector Inverse Clarke Transform',['../group__inv__clarke.html',1,'']]],
  ['vector_20inverse_20park_20transform_18',['Vector Inverse Park transform',['../group__inv__park.html',1,'']]],
  ['vector_20log_19',['Vector Log',['../group__vlog.html',1,'']]],
  ['vector_20matrix_20buffer_20allocator_20',['Vector / matrix buffer allocator',['../group__MEMVEC.html',1,'']]],
  ['vector_20multiplication_21',['Vector Multiplication',['../group__MatrixVectMult.html',1,'Matrix Vector Multiplication'],['../group__BasicMult.html',1,'Vector Multiplication']]],
  ['vector_20negate_22',['Vector Negate',['../group__BasicNegate.html',1,'']]],
  ['vector_20offset_23',['Vector Offset',['../group__BasicOffset.html',1,'']]],
  ['vector_20park_20transform_24',['Vector Park Transform',['../group__park.html',1,'']]],
  ['vector_20scale_25',['Vector Scale',['../group__BasicScale.html',1,'']]],
  ['vector_20shift_26',['Vector Shift',['../group__BasicShift.html',1,'']]],
  ['vector_20sorting_20algorithms_27',['Vector sorting algorithms',['../group__Sorting.html',1,'']]],
  ['vector_20subtraction_28',['Vector Subtraction',['../group__BasicSub.html',1,'']]],
  ['vectors_29',['Vectors',['../group__VECTOR.html',1,'']]]
];
