var searchData=
[
  ['matrix_20addition_0',['Matrix Addition',['../group__MatrixAdd.html',1,'']]],
  ['matrix_20example_1',['Matrix Example',['../group__MatrixExample.html',1,'']]],
  ['matrix_20functions_2',['Matrix Functions',['../group__groupMatrix.html',1,'']]],
  ['matrix_20initialization_3',['Matrix Initialization',['../group__MatrixInit.html',1,'']]],
  ['matrix_20inverse_4',['Matrix Inverse',['../group__MatrixInv.html',1,'']]],
  ['matrix_20multiplication_5',['Matrix Multiplication',['../group__MatrixMult.html',1,'']]],
  ['matrix_20scale_6',['Matrix Scale',['../group__MatrixScale.html',1,'']]],
  ['matrix_20subtraction_7',['Matrix Subtraction',['../group__MatrixSub.html',1,'']]],
  ['matrix_20transpose_8',['Matrix Transpose',['../group__MatrixTrans.html',1,'']]],
  ['matrix_20vector_20multiplication_9',['Matrix Vector Multiplication',['../group__MatrixVectMult.html',1,'']]],
  ['matrixes_10',['Matrixes',['../group__Matrix.html',1,'']]],
  ['maximum_11',['Maximum',['../group__Max.html',1,'']]],
  ['mean_12',['Mean',['../group__mean.html',1,'']]],
  ['mean_20square_20error_13',['Mean Square Error',['../group__MSE.html',1,'']]],
  ['memory_20allocator_14',['Memory allocator',['../group__MEMORY.html',1,'']]],
  ['memory_20buffer_20allocator_15',['Memory buffer allocator',['../group__MEMBUF.html',1,'']]],
  ['mfcc_16',['MFCC',['../group__MFCC.html',1,'']]],
  ['mfcc_20f16_17',['MFCC F16',['../group__MFCCF16.html',1,'']]],
  ['mfcc_20f32_18',['MFCC F32',['../group__MFCCF32.html',1,'']]],
  ['mfcc_20q15_19',['MFCC Q15',['../group__MFCCQ15.html',1,'']]],
  ['mfcc_20q31_20',['MFCC Q31',['../group__MFCCQ31.html',1,'']]],
  ['minimum_21',['Minimum',['../group__Min.html',1,'']]],
  ['minkowski_20distance_22',['Minkowski distance',['../group__Minkowski.html',1,'']]],
  ['miscellaneous_20utilities_20for_20memory_23',['Miscellaneous utilities for memory',['../group__MEMTOOL.html',1,'']]]
];
