var searchData=
[
  ['magnitude_0',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['magnitude_20squared_1',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['manhattan_20distance_2',['Cityblock (Manhattan) distance',['../group__Manhattan.html',1,'']]],
  ['marks_20example_3',['Class Marks Example',['../group__ClassMarks.html',1,'']]],
  ['math_20functions_4',['Math Functions',['../group__groupMath.html',1,'Basic Math Functions'],['../group__groupCmplxMath.html',1,'Complex Math Functions'],['../group__groupFastMath.html',1,'Fast Math Functions'],['../group__groupQuaternionMath.html',1,'Quaternion Math Functions']]],
  ['matrix_5',['QR decomposition of a Matrix',['../group__MatrixQR.html',1,'']]],
  ['matrix_20addition_6',['Matrix Addition',['../group__MatrixAdd.html',1,'']]],
  ['matrix_20buffer_20allocator_7',['Vector / matrix buffer allocator',['../group__MEMVEC.html',1,'']]],
  ['matrix_20example_8',['Matrix Example',['../group__MatrixExample.html',1,'']]],
  ['matrix_20functions_9',['Matrix Functions',['../group__groupMatrix.html',1,'']]],
  ['matrix_20initialization_10',['Matrix Initialization',['../group__MatrixInit.html',1,'']]],
  ['matrix_20inverse_11',['Matrix Inverse',['../group__MatrixInv.html',1,'']]],
  ['matrix_20multiplication_12',['Matrix Multiplication',['../group__CmplxMatrixMult.html',1,'Complex Matrix Multiplication'],['../group__MatrixMult.html',1,'Matrix Multiplication']]],
  ['matrix_20scale_13',['Matrix Scale',['../group__MatrixScale.html',1,'']]],
  ['matrix_20subtraction_14',['Matrix Subtraction',['../group__MatrixSub.html',1,'']]],
  ['matrix_20transpose_15',['Matrix Transpose',['../group__MatrixComplexTrans.html',1,'Complex Matrix Transpose'],['../group__MatrixTrans.html',1,'Matrix Transpose']]],
  ['matrix_20vector_20multiplication_16',['Matrix Vector Multiplication',['../group__MatrixVectMult.html',1,'']]],
  ['matrixes_17',['Matrixes',['../group__Matrix.html',1,'']]],
  ['maximum_18',['Maximum',['../group__AbsMax.html',1,'Absolute Maximum'],['../group__Max.html',1,'Maximum']]],
  ['mean_19',['Mean',['../group__mean.html',1,'']]],
  ['mean_20square_20error_20',['Mean Square Error',['../group__MSE.html',1,'']]],
  ['mean_20square_20lms_20filters_21',['Least Mean Square (LMS) Filters',['../group__LMS.html',1,'']]],
  ['mean_20square_20rms_22',['Root mean square (RMS)',['../group__RMS.html',1,'']]],
  ['memory_23',['Miscellaneous utilities for memory',['../group__MEMTOOL.html',1,'']]],
  ['memory_20allocator_24',['Memory allocator',['../group__MEMORY.html',1,'']]],
  ['memory_20allocator_20example_25',['DSP++ Vector and Memory Allocator Example',['../group__DspppExample.html',1,'']]],
  ['memory_20buffer_20allocator_26',['Memory buffer allocator',['../group__MEMBUF.html',1,'']]],
  ['mfcc_27',['MFCC',['../group__MFCCBuffers.html',1,'Buffer Sizes for MFCC'],['../group__MFCC.html',1,'MFCC']]],
  ['mfcc_20f16_28',['MFCC F16',['../group__MFCCF16.html',1,'']]],
  ['mfcc_20f32_29',['MFCC F32',['../group__MFCCF32.html',1,'']]],
  ['mfcc_20q15_30',['MFCC Q15',['../group__MFCCQ15.html',1,'']]],
  ['mfcc_20q31_31',['MFCC Q31',['../group__MFCCQ31.html',1,'']]],
  ['minimum_32',['Minimum',['../group__AbsMin.html',1,'Absolute Minimum'],['../group__Min.html',1,'Minimum']]],
  ['minkowski_20distance_33',['Minkowski distance',['../group__Minkowski.html',1,'']]],
  ['miscellaneous_20utilities_20for_20memory_34',['Miscellaneous utilities for memory',['../group__MEMTOOL.html',1,'']]],
  ['motor_20control_35',['PID Motor Control',['../group__PID.html',1,'']]],
  ['multiplication_36',['Multiplication',['../group__CmplxMatrixMult.html',1,'Complex Matrix Multiplication'],['../group__CmplxByCmplxMult.html',1,'Complex-by-Complex Multiplication'],['../group__CmplxByRealMult.html',1,'Complex-by-Real Multiplication'],['../group__MatrixMult.html',1,'Matrix Multiplication'],['../group__MatrixVectMult.html',1,'Matrix Vector Multiplication'],['../group__BasicMult.html',1,'Vector Multiplication']]]
];
