var searchData=
[
  ['rbf_20svm_0',['RBF SVM',['../group__rbfsvm.html',1,'']]],
  ['real_20fft_20f16_20functions_1',['Real FFT F16 Functions',['../group__RealFFTF16.html',1,'']]],
  ['real_20fft_20f32_20functions_2',['Real FFT F32 Functions',['../group__RealFFTF32.html',1,'']]],
  ['real_20fft_20f64_20functions_3',['Real FFT F64 Functions',['../group__RealFFTF64.html',1,'']]],
  ['real_20fft_20functions_4',['Real FFT Functions',['../group__DeprecatedRealFFT.html',1,'Deprecated Real FFT Functions'],['../group__RealFFT.html',1,'Real FFT Functions']]],
  ['real_20fft_20q15_20functions_5',['Real FFT Q15 Functions',['../group__RealFFTQ15.html',1,'']]],
  ['real_20fft_20q31_20functions_6',['Real FFT Q31 Functions',['../group__RealFFTQ31.html',1,'']]],
  ['real_20fft_20tables_7',['Real FFT Tables',['../group__RealFFT__Table.html',1,'']]],
  ['real_20multiplication_8',['Complex-by-Real Multiplication',['../group__CmplxByRealMult.html',1,'']]],
  ['regular_20window_20functions_9',['Regular window functions',['../group__WindowNormal.html',1,'']]],
  ['response_20fir_20decimator_10',['Finite Impulse Response (FIR) Decimator',['../group__FIR__decimate.html',1,'']]],
  ['response_20fir_20filters_11',['Finite Impulse Response (FIR) Filters',['../group__FIR.html',1,'']]],
  ['response_20fir_20interpolator_12',['Finite Impulse Response (FIR) Interpolator',['../group__FIR__Interpolate.html',1,'']]],
  ['response_20fir_20lattice_20filters_13',['Finite Impulse Response (FIR) Lattice Filters',['../group__FIR__Lattice.html',1,'']]],
  ['response_20fir_20sparse_20filters_14',['Finite Impulse Response (FIR) Sparse Filters',['../group__FIR__Sparse.html',1,'']]],
  ['response_20iir_20lattice_20filters_15',['Infinite Impulse Response (IIR) Lattice Filters',['../group__IIR__Lattice.html',1,'']]],
  ['rfft_16',['Buffer Sizes for RFFT',['../group__RFFTBuffers.html',1,'']]],
  ['rms_17',['Root mean square (RMS)',['../group__RMS.html',1,'']]],
  ['root_18',['Square Root',['../group__SQRT.html',1,'']]],
  ['root_20mean_20square_20rms_19',['Root mean square (RMS)',['../group__RMS.html',1,'']]],
  ['rotation_20',['Quaternion to Rotation',['../group__QuatRot.html',1,'']]],
  ['rotation_20to_20quaternion_21',['Rotation to Quaternion',['../group__RotQuat.html',1,'']]]
];
