var searchData=
[
  ['variance_0',['Variance',['../group__variance.html',1,'']]],
  ['variance_20example_1',['Variance Example',['../group__VarianceExample.html',1,'']]],
  ['vector_20_2f_20matrix_20buffer_20allocator_2',['Vector / matrix buffer allocator',['../group__MEMVEC.html',1,'']]],
  ['vector_20absolute_20value_3',['Vector Absolute Value',['../group__BasicAbs.html',1,'']]],
  ['vector_20addition_4',['Vector Addition',['../group__BasicAdd.html',1,'']]],
  ['vector_20bitwise_20and_5',['Vector bitwise AND',['../group__And.html',1,'']]],
  ['vector_20bitwise_20exclusive_20or_6',['Vector bitwise exclusive OR',['../group__Xor.html',1,'']]],
  ['vector_20bitwise_20inclusive_20or_7',['Vector bitwise inclusive OR',['../group__Or.html',1,'']]],
  ['vector_20bitwise_20not_8',['Vector bitwise NOT',['../group__Not.html',1,'']]],
  ['vector_20clarke_20transform_9',['Vector Clarke Transform',['../group__clarke.html',1,'']]],
  ['vector_20copy_10',['Vector Copy',['../group__copy.html',1,'']]],
  ['vector_20dot_20product_11',['Vector Dot Product',['../group__BasicDotProd.html',1,'']]],
  ['vector_20exponential_12',['Vector Exponential',['../group__vexp.html',1,'']]],
  ['vector_20fill_13',['Vector Fill',['../group__Fill.html',1,'']]],
  ['vector_20inverse_20clarke_20transform_14',['Vector Inverse Clarke Transform',['../group__inv__clarke.html',1,'']]],
  ['vector_20inverse_20park_20transform_15',['Vector Inverse Park transform',['../group__inv__park.html',1,'']]],
  ['vector_20log_16',['Vector Log',['../group__vlog.html',1,'']]],
  ['vector_20multiplication_17',['Vector Multiplication',['../group__BasicMult.html',1,'']]],
  ['vector_20negate_18',['Vector Negate',['../group__BasicNegate.html',1,'']]],
  ['vector_20offset_19',['Vector Offset',['../group__BasicOffset.html',1,'']]],
  ['vector_20park_20transform_20',['Vector Park Transform',['../group__park.html',1,'']]],
  ['vector_20scale_21',['Vector Scale',['../group__BasicScale.html',1,'']]],
  ['vector_20shift_22',['Vector Shift',['../group__BasicShift.html',1,'']]],
  ['vector_20sorting_20algorithms_23',['Vector sorting algorithms',['../group__Sorting.html',1,'']]],
  ['vector_20subtraction_24',['Vector Subtraction',['../group__BasicSub.html',1,'']]],
  ['vectors_25',['Vectors',['../group__VECTOR.html',1,'']]]
];
