/* Copyright (c) 2022 Google Inc
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef INCLUDE_CMSIS_DSP_MATH_TYPES_H_
#define INCLUDE_CMSIS_DSP_MATH_TYPES_H_

#include "arm_math_types.h"

#define CMSIS_MATH_SUCCESS ARM_MATH_SUCCESS
#define CMSIS_MATH_ARGUMENT_ERROR ARM_MATH_ARGUMENT_ERROR
#define CMSIS_MATH_LENGTH_ERROR ARM_MATH_LENGTH_ERROR
#define CMSIS_MATH_SIZE_MISMATCH ARM_MATH_SIZE_MISMATH
#define CMSIS_MATH_MANIF ARM_MATH_MANIF
#define CMSIS_MATH_TEST_FAILURE ARM_MATH_TEST_FAILURE
#define CMSIS_MATH_DECOMPOSITION_FAILURE ARM_MATH_DECOMPOSITION_FAILURE

#endif /* INCLUDE_CMSIS_DSP_MATH_TYPES_H_ */
